### ISSUE TITLE
(Request) Elden Ring FLVER to FBX: Mesh names

### ISSUE THREAD

**Issue by ividyon** [Shadowth117/PSO2-Aqua-Library#2]
Hi,

thank you for your work on AMT.

![image](https://user-images.githubusercontent.com/1077140/225607240-97da957a-df25-4f4e-b4af-b2d174e74112.png)

Here's a screenshot from The12thAvenger's FbxImporter tool. On the left are the meshes inside a FLVER, on the right are the same meshes from the FBX generated by AMT when turning the FLVER to FBX.

The FBX has lost the unique names of the FLVER meshes, which are very important for functionality. The `#Number#` denotes a model mask which can be toggled ingame for different reasons (enemy variants, LOD), and `_cloth` denotes that this mesh will be controlled by Havok physics.

Unless I'm mistaken (I looked into the FBX with a hex editor), the `mesh[0]` naming is inside the FBX file, rather than a result of importing/exporting the FBX with Blender.

You already have the correct names at hand in the FBX inside the Materials:

![image](https://user-images.githubusercontent.com/1077140/225607928-c0543f72-b1ac-4ef7-9458-1cbc4a5fd4a0.png)

This is the material for the `#15#BD_skirt_cloth` mesh, which is called `mesh[4]` in the FBX.

Would it be possible for the AMT exporter to apply that part of the material name to the actual mesh as well?

**Comment by Shadowth117** [comment]
So the thing is, flver meshes just don't have names, this seems to all be material naming data.
Nothing was 'lost' here, it was simply not written that way. 

As far as making this easier to work with, I could try and have it generate names similar to this as an optional thing, but I don't really like how the models are exported without a number to denote their order since names are clearly not unique to a mesh even in your screenshot. If the exact name is not important I would very much prefer to do "{mat_name}_mesh{meshNum}".

**Comment by Shadowth117** [comment]
Latest commit adds an option for this. Closing.
