### ISSUE TITLE
Exception in FbxExporterCore.ExportToFile on Specific File

### ISSUE THREAD

**Issue by HelloKitty** [Shadowth117/PSO2-Aqua-Library#6]
Sometimes the PSO2 FBX Export will encounter an exception on some select files.

Currently, this file I know of at the moment: the pl_bd_2638_x_ml_ow file from 75f38308dc21b52005a08b8e29d38bb2

```
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at AquaModelLibrary.Objects.Processing.Fbx.FbxExporterCore.ExportToFile(AquaObject aqo, AquaNode aqn, List`1 aqmList, String destinationFilePath, List`1 aqmNameList, List`1 instanceTransforms, Boolean includeMetadata)
```

**Comment by Shadowth117** [comment]
Fixed in this build:
[https://github.com/Shadowth117/PSO2-Aqua-Library/releases/tag/10_1_2023](https://github.com/Shadowth117/PSO2-Aqua-Library/releases/tag/10_1_2023)

This was made under the assumption that a parent couldn't be a node that only came after the current node in the list so I'm surprised we never found this sooner. Good find.
